name: learn-github-actions
on: [push]
# on:
#   pull_request:
#     types: [opened, reopened ]
#     branched: 
#     - dev
jobs:
  # test_job1:
  #   runs-on: [self-hosted, test]
  #   steps: 
  #   - uses: actions/checkout@v3
  #     with: 
  #       ref: '${GITHUB_HEAD_REF}'
  #   - run: echo pull request opened....
  #   - run: cat a.py
 test_job1:
   runs-on: [self-hosted, test]
   steps:
     - uses: actions/checkout@master
     - uses: travisj/build-number-action@v1
       id: project-build-number
     - run: pwd
     - run: ls ./
     - run: echo ${{ steps.project-build-number.outputs.build-number }}
#  test_job2:
#    runs-on: [self-hosted, test]
#    container:
#      image: registry.cn-hangzhou.aliyuncs.com/mhc_base/net-tools:latest
#      env:
#        NODE_ENV: development
#      ports:
#        - 80
# #      volumes:
# #        - my_docker_volume:/volume_mount
#      options: --cpus 1
  #  steps:
  #    - uses: actions/checkout@master
  #    - run: pwd
  #    - run: ls ./
  #    - run: ls /
  #    - run: echo $NODE_ENV
#   test_job3:
#     runs-on: [self-hosted, test]
#     services:
#       nginx:
#         image: nginx
#         ports:
#           - 8080:80
#     container:
#       image: centos:7
#       env:
#         NODE_ENV: development
#       ports:
#         - 80
# #      volumes:
# #        - my_docker_volume:/volume_mount
#       options: --cpus 1
#     steps:
#       - run: curl nginx:80
