name: other
jobs:
 test_job1:
   runs-on: [self-hosted, test]
   steps:
     - run: echo ahahah..................
     - run: ls ./
     - run: ls /
     - run: echo $NODE_ENV
#   test_job3:
#     runs-on: [self-hosted, test]
#     services:
#       nginx:
#         image: nginx
#         ports:
#           - 8080:80
#     container:
#       image: centos:7
#       env:
#         NODE_ENV: development
#       ports:
#         - 80
# #      volumes:
# #        - my_docker_volume:/volume_mount
#       options: --cpus 1
#     steps:
#       - run: curl nginx:80
